Algoritmo "Exercicio2"
//  
//  

Var
numeroUm,numeroDois,numeroTres,numeroQuatro: inteiro
multiplicacao,soma: inteiro

Inicio
escreva("Por favor digie quatro numeros")
leia(numeroUm,numeroDois,numeroTres,numeroQuatro)
multiplicacao :=numeroUm * numeroTres
soma := numeroDois + numeroQuatro
escreva("Resultado da soma: ",soma, " Resultado da muulplicação ",multiplicacao)

Fimalgoritmo
